-- ============================================================
-- Baseline: المخطط الكامل لقاعدة بيانات نظام الأقصى
-- ============================================================
-- مُستخرَجة بالاستقراء من pg_catalog على قاعدة الإنتاج.
-- تمثّل الحالة الكاملة: الجداول والأعمدة والمفاتيح والقيود
-- والفهارس والدوال والسياسات والصلاحيات وحاوية التخزين.
--
-- الملف idempotent بالكامل (IF NOT EXISTS / OR REPLACE / حُرّاس DO)،
-- فتشغيله على قاعدة قائمة لا يفعل شيئاً ولا يفشل.
--
-- لا يُنشئ: delete_empty_financial_group() والمحفّز الخاص به،
-- ولا create_financial_group_with_member() — هذه تنشئها
-- migrations لاحقة بتاريخ 20260731.
--
-- لا يحتوي أي بيانات. لا INSERT ولا DELETE ولا UPDATE.

-- ── الامتدادات ──────────────────────────────────────────────
create schema if not exists extensions;
create extension if not exists pgcrypto   with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;

-- ── الجداول ─────────────────────────────────────────────────
create table if not exists public.seasons (
  id          bigint generated always as identity primary key,
  name        text not null,
  created_at  timestamptz default now(),
  closed_at   timestamptz,
  closed_by   text
);

create table if not exists public.users (
  id          bigint generated always as identity primary key,
  created_at  timestamptz default now(),
  username    text not null,
  password    text not null,
  name        text not null,
  permissions jsonb default '{}'::jsonb,
  is_active   boolean default true
);

create table if not exists public.buses (
  id         bigint generated always as identity primary key,
  created_at timestamptz default now(),
  name       text,
  type       text default 'عادي'::text,
  season_id  bigint,
  capacity   integer default 50
);

create table if not exists public.camps (
  id         bigint generated always as identity primary key,
  created_at timestamptz default now(),
  name       text,
  gender     text,
  type       text default 'عادي'::text,
  page_type  text,
  season_id  bigint
);

create table if not exists public.rooms (
  id         bigint generated always as identity primary key,
  created_at timestamptz default now(),
  number     text,
  floor      text,
  type       text default 'مطل'::text,
  season_id  bigint,
  notes      text
);

create table if not exists public.flights (
  id           bigint generated always as identity primary key,
  name         text,
  airline      text,
  date         text,
  time         text,
  from_airport text,
  to_airport   text,
  created_at   timestamptz default now(),
  type         text,
  arrival_time text,
  arrival_date text
);

create table if not exists public.passengers (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  name_ar           text,
  name_en           text,
  short_en          text,
  passport          text,
  national_id       text,
  nat               text,
  dob               text,
  expiry            text,
  gender            text,
  phone             text,
  bus               text,
  flight            text,
  camp_mina         text,
  camp_arafa        text,
  photo_url         text,
  passport_url      text,
  national_id_url   text,
  contract_url      text,
  short_ar          text,
  id_expiry         text,
  bus_id            bigint,
  camp_mina_id      bigint,
  camp_arafa_id     bigint,
  room_id           bigint,
  family_id         text,
  season_id         bigint,
  hotel_type        text,
  hotel_view        text,
  flight_class      text,
  flight_id         bigint,
  sort_order        integer default 0,
  created_by        text,
  updated_by        text,
  updated_at        timestamptz,
  return_flight_id  bigint,
  passenger_type    text default 'حاج'::text,
  custom_price      numeric default 0,
  hajj_permit_url   text,
  flight_ticket_url text,
  wants_flight      boolean default false
);

create table if not exists public.company_config (
  id                 integer not null default 1 primary key,
  name_ar            text not null default 'نظام الحج'::text,
  name_en            text default 'Hajj System'::text,
  tagline            text default 'نظام إدارة الحج'::text,
  logo_url           text,
  color_primary      text default '#1D9E75'::text,
  color_accent       text default '#085041'::text,
  color_sidebar      text default '#f9f9f9'::text,
  contact_phone      text,
  contact_email      text,
  season_label       text default 'موسم الحج ١٤٤٧ هـ'::text,
  features           jsonb default '{"scan": true, "buses": true, "hotel": true, "users": true, "archive": true, "reports": true, "camps_mina": true, "camps_arafa": true}'::jsonb,
  banner_image_url   text,
  banner_position    text default 'center'::text,
  banner_position_x  text default '50'::text,
  admin_name         text,
  admin_phone        text,
  admin_whatsapp     text,
  country            text,
  city               text,
  hotel_name         text,
  hotel_address      text,
  camp_mina_address  text,
  camp_arafa_address text,
  hotel_url          text,
  camp_mina_url      text,
  camp_arafa_url     text
);

create table if not exists public.pricing_settings (
  id         serial primary key,
  key        text not null,
  label      text not null,
  amount     numeric(10,2) not null default 0,
  type       text not null,
  updated_at timestamptz default now()
);

create table if not exists public.payments (
  id           serial primary key,
  passenger_id integer not null,
  amount       numeric(10,2) not null,
  payment_date date not null default CURRENT_DATE,
  method       text not null default 'نقدي'::text,
  notes        text,
  created_by   text,
  created_at   timestamptz default now()
);

create table if not exists public.custom_charges (
  id           serial primary key,
  passenger_id integer not null,
  description  text not null,
  amount       numeric(10,2) not null,
  type         text not null,
  notes        text,
  created_by   text,
  created_at   timestamptz default now()
);

create table if not exists public.financial_groups (
  id         serial primary key,
  name       text not null,
  notes      text,
  created_by text,
  created_at timestamptz default now()
);

create table if not exists public.financial_group_members (
  id           serial primary key,
  group_id     integer not null,
  passenger_id integer not null
);

create table if not exists public.announcements (
  id           bigint generated always as identity primary key,
  body         text not null,
  priority     text not null default 'عام'::text,
  show_at      timestamptz not null default now(),
  expires_at   timestamptz,
  created_by   text,
  created_at   timestamptz default now(),
  title        text,
  target_type  text not null default 'all'::text,
  target_ids   bigint[] not null default '{}'::bigint[],
  push_sent_at timestamptz
);

create table if not exists public.notification_deliveries (
  id              bigserial primary key,
  announcement_id bigint not null,
  passenger_id    bigint not null,
  status          text not null default 'pending'::text,
  error           text,
  sent_at         timestamptz not null default now(),
  read_at         timestamptz
);

create table if not exists public.pilgrim_push_subscriptions (
  id           bigserial primary key,
  passenger_id bigint not null,
  endpoint     text not null,
  p256dh       text not null,
  auth         text not null,
  platform     text not null default 'web'::text,
  user_agent   text,
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

-- ── القيود (مفاتيح أجنبية / تفرّد / فحص) ────────────────────
do $$
declare
  c record;
begin
  for c in
    select * from (values
      ('payments','payments_passenger_id_fkey',
       'foreign key (passenger_id) references public.passengers(id) on delete cascade'),
      ('payments','payments_method_check',
       'check (method = any (array[''نقدي''::text, ''تحويل بنكي''::text, ''شيك''::text]))'),
      ('custom_charges','custom_charges_passenger_id_fkey',
       'foreign key (passenger_id) references public.passengers(id) on delete cascade'),
      ('custom_charges','custom_charges_type_check',
       'check (type = any (array[''إضافة''::text, ''خصم''::text]))'),
      ('pricing_settings','pricing_settings_key_key','unique (key)'),
      ('pricing_settings','pricing_settings_type_check',
       'check (type = any (array[''package''::text, ''addon''::text, ''discount''::text]))'),
      ('users','users_username_key','unique (username)'),
      ('financial_group_members','financial_group_members_group_id_fkey',
       'foreign key (group_id) references public.financial_groups(id) on delete cascade'),
      ('financial_group_members','financial_group_members_passenger_id_fkey',
       'foreign key (passenger_id) references public.passengers(id) on delete cascade'),
      ('financial_group_members','financial_group_members_group_id_passenger_id_key',
       'unique (group_id, passenger_id)'),
      ('financial_group_members','financial_group_members_passenger_id_key',
       'unique (passenger_id)'),
      ('notification_deliveries','notification_deliveries_announcement_id_fkey',
       'foreign key (announcement_id) references public.announcements(id) on delete cascade'),
      ('notification_deliveries','notification_deliveries_passenger_id_fkey',
       'foreign key (passenger_id) references public.passengers(id) on delete cascade'),
      ('notification_deliveries','notification_deliveries_announcement_id_passenger_id_key',
       'unique (announcement_id, passenger_id)'),
      ('pilgrim_push_subscriptions','pilgrim_push_subscriptions_passenger_id_fkey',
       'foreign key (passenger_id) references public.passengers(id) on delete cascade'),
      ('pilgrim_push_subscriptions','pilgrim_push_subscriptions_endpoint_key','unique (endpoint)')
    ) as t(tbl, name, def)
  loop
    if not exists (
      select 1 from pg_constraint pc
      join pg_class rel on rel.oid = pc.conrelid
      join pg_namespace n on n.oid = rel.relnamespace
      where n.nspname = 'public' and rel.relname = c.tbl and pc.conname = c.name
    ) then
      execute format('alter table public.%I add constraint %I %s', c.tbl, c.name, c.def);
    end if;
  end loop;
end $$;

-- ── الفهارس غير المرتبطة بقيود ──────────────────────────────
create index if not exists idx_passengers_sort_order on public.passengers using btree (sort_order);
create index if not exists idx_nd_announcement       on public.notification_deliveries using btree (announcement_id);
create index if not exists idx_nd_passenger          on public.notification_deliveries using btree (passenger_id);
create index if not exists idx_pps_passenger         on public.pilgrim_push_subscriptions using btree (passenger_id);

-- ── الدوال ──────────────────────────────────────────────────
create or replace function public.verify_user(p_username text, p_password text)
returns table(id bigint, name text, username text, password text, permissions jsonb)
language sql
security definer
as $$
  SELECT id, name, username, password, permissions
  FROM users
  WHERE username = p_username
  AND password = crypt(p_password, password);
$$;

create or replace function public.create_user(p_name text, p_username text, p_password text, p_permissions jsonb)
returns void
language plpgsql
security definer
as $$
BEGIN
  INSERT INTO users (name, username, password, permissions)
  VALUES (p_name, p_username, crypt(p_password, gen_salt('bf')), p_permissions);
END;
$$;

create or replace function public.update_user(p_id integer, p_name text, p_username text, p_password text, p_permissions jsonb)
returns void
language plpgsql
security definer
as $$
BEGIN
  UPDATE users SET
    name = p_name,
    username = p_username,
    password = crypt(p_password, gen_salt('bf')),
    permissions = p_permissions
  WHERE id = p_id;
END;
$$;

create or replace function public.resolve_pilgrim_id(p_doc text, p_day integer, p_month integer, p_year integer)
returns bigint
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_id bigint; v_dob text; v_nums text[]; v_y int; v_m int; v_d int;
begin
  for v_id, v_dob in
    select id, coalesce(dob, '') from passengers
    where trim(coalesce(passport, ''))    = trim(p_doc)
       or trim(coalesce(national_id, '')) = trim(p_doc)
  loop
    v_nums := array_remove(
      regexp_split_to_array(regexp_replace(v_dob, '[^0-9]+', ' ', 'g'), '\s+'), '');
    if array_length(v_nums, 1) = 3 then
      if length(v_nums[1]) = 4 then
        v_y := v_nums[1]::int; v_m := v_nums[2]::int; v_d := v_nums[3]::int;
      else
        v_d := v_nums[1]::int; v_m := v_nums[2]::int; v_y := v_nums[3]::int;
      end if;
      if v_y = p_year and v_m = p_month and v_d = p_day then
        return v_id;
      end if;
    end if;
  end loop;
  return null;
end; $$;

create or replace function public.announcement_audience(p_target_type text, p_target_ids bigint[])
returns table(passenger_id bigint)
language sql
stable
security definer
set search_path to 'public'
as $$
  select p.id from passengers p
  where (
      p.season_id is null
      or p.season_id = (select s.id from seasons s where s.closed_at is null order by s.id desc limit 1)
    )
    and case coalesce(p_target_type, 'all')
          when 'bus'        then p.bus_id        = any(p_target_ids)
          when 'camp_mina'  then p.camp_mina_id  = any(p_target_ids)
          when 'camp_arafa' then p.camp_arafa_id = any(p_target_ids)
          when 'custom'     then p.id            = any(p_target_ids)
          else true
        end;
$$;

create or replace function public.push_enabled_passengers()
returns table(passenger_id bigint, devices bigint)
language sql
stable
security definer
set search_path to 'public'
as $$
  select s.passenger_id, count(*)::bigint
  from pilgrim_push_subscriptions s
  group by s.passenger_id;
$$;

create or replace function public.register_pilgrim_push(
  p_doc text, p_day integer, p_month integer, p_year integer,
  p_endpoint text, p_p256dh text, p_auth text,
  p_platform text default 'web'::text, p_user_agent text default null::text)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $$
declare v_pid bigint;
begin
  v_pid := resolve_pilgrim_id(p_doc, p_day, p_month, p_year);
  if v_pid is null then return false; end if;

  insert into pilgrim_push_subscriptions
    (passenger_id, endpoint, p256dh, auth, platform, user_agent)
  values
    (v_pid, p_endpoint, p_p256dh, p_auth, coalesce(p_platform, 'web'), p_user_agent)
  on conflict (endpoint) do update set
    passenger_id = excluded.passenger_id,
    p256dh       = excluded.p256dh,
    auth         = excluded.auth,
    platform     = excluded.platform,
    user_agent   = excluded.user_agent,
    last_seen_at = now();

  return true;
end; $$;

create or replace function public.unregister_pilgrim_push(p_endpoint text)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  delete from pilgrim_push_subscriptions where endpoint = p_endpoint;
  return true;
end; $$;

create or replace function public.mark_pilgrim_notification_read(
  p_doc text, p_day integer, p_month integer, p_year integer, p_announcement_id bigint)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $$
declare v_pid bigint;
begin
  v_pid := resolve_pilgrim_id(p_doc, p_day, p_month, p_year);
  if v_pid is null then return false; end if;

  insert into notification_deliveries (announcement_id, passenger_id, status, read_at)
  values (p_announcement_id, v_pid, 'read', now())
  on conflict (announcement_id, passenger_id) do update
    set read_at = coalesce(notification_deliveries.read_at, now());

  return true;
end; $$;

create or replace function public.get_pilgrim_portal(p_doc text, p_day integer, p_month integer, p_year integer)
returns json
language plpgsql
security definer
as $$
DECLARE
  v_p passengers%ROWTYPE;
  v_matched boolean := false;
  v_nums text[];
  v_y int; v_m int; v_d int;
  v_result json;
BEGIN
  FOR v_p IN
    SELECT * FROM passengers
    WHERE trim(coalesce(passport,'')) = trim(p_doc)
       OR trim(coalesce(national_id,'')) = trim(p_doc)
  LOOP
    v_nums := regexp_split_to_array(regexp_replace(coalesce(v_p.dob,''), '[^0-9]+', ' ', 'g'), '\s+');
    v_nums := array_remove(v_nums, '');
    IF array_length(v_nums,1) = 3 THEN
      IF length(v_nums[1]) = 4 THEN
        v_y := v_nums[1]::int; v_m := v_nums[2]::int; v_d := v_nums[3]::int;
      ELSE
        v_d := v_nums[1]::int; v_m := v_nums[2]::int; v_y := v_nums[3]::int;
      END IF;
      IF v_y = p_year AND v_m = p_month AND v_d = p_day THEN
        v_matched := true;
        EXIT;
      END IF;
    END IF;
  END LOOP;

  IF NOT v_matched THEN RETURN NULL; END IF;

  SELECT json_build_object(
    'pilgrim', json_build_object(
      'name_ar', v_p.name_ar, 'short_ar', v_p.short_ar, 'name_en', v_p.name_en,
      'gender', v_p.gender, 'photo_url', v_p.photo_url,
      'hajj_permit_url', v_p.hajj_permit_url, 'flight_ticket_url', v_p.flight_ticket_url,
      'hotel_type', v_p.hotel_type, 'hotel_view', v_p.hotel_view,
      'camp_mina', v_p.camp_mina, 'camp_arafa', v_p.camp_arafa,
      'camp_mina_name', (SELECT c.name FROM camps c WHERE c.id = v_p.camp_mina_id),
      'camp_arafa_name', (SELECT c.name FROM camps c WHERE c.id = v_p.camp_arafa_id),
      'phone', v_p.phone
    ),
    'bus', (SELECT json_build_object('name', b.name, 'type', b.type) FROM buses b WHERE b.id = v_p.bus_id),
    'room', (SELECT json_build_object('number', r.number, 'floor', r.floor, 'type', r.type) FROM rooms r WHERE r.id = v_p.room_id),
    'roommates', CASE
      WHEN v_p.room_id IS NOT NULL THEN
        (SELECT coalesce(json_agg(json_build_object(
          'name', pp.name_ar, 'short_ar', pp.short_ar,
          'room_number', r2.number, 'room_floor', r2.floor,
          'bus_name', b2.name,
          'is_family', (pp.family_id IS NOT NULL AND pp.family_id = v_p.family_id)
        )), '[]'::json)
         FROM passengers pp
         LEFT JOIN rooms r2 ON r2.id = pp.room_id
         LEFT JOIN buses b2 ON b2.id = pp.bus_id
         WHERE pp.room_id = v_p.room_id AND pp.id <> v_p.id)
      ELSE '[]'::json END,
    'family', CASE
      WHEN v_p.family_id IS NOT NULL THEN
        (SELECT coalesce(json_agg(json_build_object(
          'name', pp.name_ar, 'short_ar', pp.short_ar,
          'gender', pp.gender,
          'room_number', r2.number, 'room_floor', r2.floor,
          'bus_name', b2.name,
          'camp_mina_name', (SELECT c.name FROM camps c WHERE c.id = pp.camp_mina_id),
          'camp_arafa_name', (SELECT c.name FROM camps c WHERE c.id = pp.camp_arafa_id)
        )), '[]'::json)
         FROM passengers pp
         LEFT JOIN rooms r2 ON r2.id = pp.room_id
         LEFT JOIN buses b2 ON b2.id = pp.bus_id
         WHERE pp.family_id = v_p.family_id AND pp.id <> v_p.id)
      ELSE '[]'::json END,
    'flight_go', (SELECT json_build_object('name', f.name, 'airline', f.airline, 'from_airport', f.from_airport, 'to_airport', f.to_airport, 'date', f.date, 'time', f.time, 'arrival_time', f.arrival_time, 'arrival_date', f.arrival_date, 'class', v_p.flight_class) FROM flights f WHERE f.id = v_p.flight_id),
    'flight_back', (SELECT json_build_object('name', f.name, 'airline', f.airline, 'from_airport', f.from_airport, 'to_airport', f.to_airport, 'date', f.date, 'time', f.time, 'arrival_time', f.arrival_time, 'arrival_date', f.arrival_date, 'class', v_p.flight_class) FROM flights f WHERE f.id = v_p.return_flight_id),
    'config', (SELECT json_build_object(
      'name_ar', c.name_ar, 'logo_url', c.logo_url, 'tagline', c.tagline,
      'color_primary', c.color_primary, 'color_accent', c.color_accent,
      'season_label', c.season_label, 'admin_name', c.admin_name,
      'admin_phone', c.admin_phone, 'admin_whatsapp', c.admin_whatsapp,
      'features', c.features, 'country', c.country, 'city', c.city,
      'hotel_name', c.hotel_name, 'hotel_address', c.hotel_address, 'hotel_url', c.hotel_url,
      'camp_mina_address', c.camp_mina_address, 'camp_mina_url', c.camp_mina_url,
      'camp_arafa_address', c.camp_arafa_address, 'camp_arafa_url', c.camp_arafa_url
    ) FROM company_config c ORDER BY c.id LIMIT 1),
    'announcements', (SELECT coalesce(json_agg(json_build_object('id', a.id, 'body', a.body, 'priority', a.priority, 'show_at', a.show_at) ORDER BY (a.priority = 'عاجل') DESC, a.show_at DESC), '[]'::json)
      FROM announcements a
      WHERE a.show_at <= now() AND (a.expires_at IS NULL OR a.expires_at > now()))
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- ── تفعيل RLS ───────────────────────────────────────────────
alter table public.seasons                    enable row level security;
alter table public.users                      enable row level security;
alter table public.buses                      enable row level security;
alter table public.camps                      enable row level security;
alter table public.rooms                      enable row level security;
alter table public.flights                    enable row level security;
alter table public.passengers                 enable row level security;
alter table public.company_config             enable row level security;
alter table public.pricing_settings           enable row level security;
alter table public.payments                   enable row level security;
alter table public.custom_charges             enable row level security;
alter table public.financial_groups           enable row level security;
alter table public.financial_group_members    enable row level security;
alter table public.announcements              enable row level security;
alter table public.notification_deliveries    enable row level security;
alter table public.pilgrim_push_subscriptions enable row level security;

-- ── السياسات ────────────────────────────────────────────────
-- ⚠️ هذه السياسات مفتوحة (USING true) وتمثّل الحالة الحالية كما هي.
--    تشديدها عمل منفصل مقصود — انظر تقرير المرحلة صفر الأمني.
drop policy if exists "allow all" on public.buses;
create policy "allow all" on public.buses for all using (true);

drop policy if exists "allow all" on public.camps;
create policy "allow all" on public.camps for all using (true);

drop policy if exists "allow all" on public.rooms;
create policy "allow all" on public.rooms for all using (true);

drop policy if exists "allow all" on public.flights;
create policy "allow all" on public.flights for all using (true);

drop policy if exists "allow all" on public.seasons;
create policy "allow all" on public.seasons for all using (true);

drop policy if exists "allow all" on public.users;
create policy "allow all" on public.users for all using (true);

drop policy if exists "allow all" on public.passengers;
create policy "allow all" on public.passengers for all using (true);

drop policy if exists "allow all" on public.company_config;
create policy "allow all" on public.company_config for all using (true);

drop policy if exists "allow_all_pricing" on public.pricing_settings;
create policy "allow_all_pricing" on public.pricing_settings for all using (true) with check (true);

drop policy if exists "allow_all_payments" on public.payments;
create policy "allow_all_payments" on public.payments for all using (true) with check (true);

drop policy if exists "allow_all_custom_charges" on public.custom_charges;
create policy "allow_all_custom_charges" on public.custom_charges for all using (true) with check (true);

drop policy if exists "allow_all_fg" on public.financial_groups;
create policy "allow_all_fg" on public.financial_groups for all using (true) with check (true);

drop policy if exists "allow_all_fgm" on public.financial_group_members;
create policy "allow_all_fgm" on public.financial_group_members for all using (true) with check (true);

drop policy if exists "nd_all" on public.notification_deliveries;
create policy "nd_all" on public.notification_deliveries for all using (true) with check (true);

drop policy if exists "announcements_select" on public.announcements;
create policy "announcements_select" on public.announcements for select using (true);
drop policy if exists "announcements_insert" on public.announcements;
create policy "announcements_insert" on public.announcements for insert with check (true);
drop policy if exists "announcements_update" on public.announcements;
create policy "announcements_update" on public.announcements for update using (true);
drop policy if exists "announcements_delete" on public.announcements;
create policy "announcements_delete" on public.announcements for delete using (true);

-- pilgrim_push_subscriptions: RLS مفعّل بلا سياسة عمداً — الوصول
-- يتم حصراً عبر دوال SECURITY DEFINER.

-- ── الصلاحيات ───────────────────────────────────────────────
grant usage on schema public to anon, authenticated, service_role;

grant all on table
  public.seasons, public.users, public.buses, public.camps, public.rooms,
  public.flights, public.passengers, public.company_config, public.pricing_settings,
  public.payments, public.custom_charges, public.financial_groups,
  public.financial_group_members, public.announcements, public.notification_deliveries
to anon, authenticated, service_role;

grant all on table public.pilgrim_push_subscriptions to service_role;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- resolve_pilgrim_id دالة داخلية: لا تُستدعى من العميل
revoke execute on function public.resolve_pilgrim_id(text, integer, integer, integer)
  from public, anon, authenticated;

-- ── التخزين ─────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('passengers-docs', 'passengers-docs', true, 5242880,
        array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do nothing;

drop policy if exists "Public read"   on storage.objects;
create policy "Public read"   on storage.objects for select using (bucket_id = 'passengers-docs');

drop policy if exists "Public upload" on storage.objects;
create policy "Public upload" on storage.objects for insert with check (bucket_id = 'passengers-docs');

drop policy if exists "Public delete" on storage.objects;
create policy "Public delete" on storage.objects for delete using (bucket_id = 'passengers-docs');
