#!/usr/bin/env python3
"""Deterministic synthetic dataset for the Pilgrim Portal load test.

Writes:
  loadtest/seed/seed.sql         - test-data step (NOT a migration)
  loadtest/k6/identities.json    - login identities for k6 (synthetic only)

Everything is derived from the pilgrim index, so re-running produces identical
files. No real names, documents or dates of birth: names are "<first> اختبار <n>",
documents are LT###### (main cohort) / LD###### (document cohort), a format no
real passport or national ID uses.
"""
import json, os

MAIN, DOCS = 600, 20
ROOM_CAP, BUS_CAP = 4, 50
FIRST_M = ["أحمد", "محمد", "محمود", "عمر", "علي", "حسن", "يوسف", "خالد", "طارق", "سامي"]
FIRST_F = ["فاطمة", "مريم", "زينب", "عائشة", "خديجة", "سارة", "نور", "هدى", "منى", "ليلى"]

def pilgrim(i, cohort):
    # rooms hold 4 of one gender: gender alternates per room
    gender = "ذكر" if ((i - 1) // ROOM_CAP) % 2 == 0 else "أنثى"
    first = (FIRST_M if gender == "ذكر" else FIRST_F)[i % 10]
    day, month, year = 1 + (i * 7) % 28, 1 + (i * 5) % 12, 1950 + (i * 13) % 50
    doc = f"{cohort}{i:06d}"
    return dict(i=i, doc=doc, gender=gender, name=f"{first} اختبار {i}",
                day=day, month=month, year=year, dob=f"{year:04d}-{month:02d}-{day:02d}")

def q(s):
    return "'" + s.replace("'", "''") + "'"

main = [pilgrim(i, "LT") for i in range(1, MAIN + 1)]
docs = [pilgrim(i, "LD") for i in range(1, DOCS + 1)]
root = os.path.dirname(os.path.abspath(__file__))

rows = []
for p in main:
    i = p["i"]
    room = (i - 1) // ROOM_CAP + 1                     # 150 rooms
    bus = (i - 1) // BUS_CAP + 1                       # 12 buses
    fam = f"'LTF{(i - 1) // 3 + 1:03d}'" if i <= 360 else "null"   # 120 families of 3
    rows.append(f"({q(p['doc'])},{q(p['name'])},{q(p['gender'])},{q(p['dob'])},{room},{bus},{fam},{i % 2})")
doc_rows = []
for p in docs:
    k = f"loadtest/{p['doc']}"
    doc_rows.append(f"({q(p['doc'])},{q(p['name'])},{q(p['gender'])},{q(p['dob'])},"
                    f"{q(k + '/photo.png')},{q(k + '/permit.pdf')},{q(k + '/ticket.pdf')})")

sql = f"""-- GENERATED by loadtest/seed/generate.py - do not edit by hand.
-- Load-test DATA step for the disposable load-test project. NOT a migration.
-- Refuses to run on any database that holds non-synthetic pilgrims or seasons.
begin;
do $$
begin
  if exists (select 1 from public.passengers where coalesce(passport,'') !~ '^L[TD][0-9]{{6}}$') then
    raise exception 'REFUSING: non-synthetic passengers present - this is not the load-test project';
  end if;
  if exists (select 1 from public.seasons where name <> 'LT-1447') then
    raise exception 'REFUSING: non-synthetic season present - this is not the load-test project';
  end if;
  if exists (select 1 from public.seasons where name = 'LT-1447') then
    raise exception 'REFUSING: synthetic season already seeded - run loadtest/sql/cleanup.sql first';
  end if;
end $$;

insert into public.seasons (name, hijri_year, hotel_name, hotel_address, mina_address, arafa_address)
values ('LT-1447', 1447, 'فندق الاختبار', 'عنوان اختباري', 'منى - اختبار', 'عرفة - اختبار');

create temp table lt_season on commit drop as select id from public.seasons where name = 'LT-1447';

update public.company_config set name_ar = 'شركة اختبار الحمل', color_primary = '#1D9E75', color_accent = '#C8A24B',
  portal_welcome_message = null, portal_help_message = null;

insert into public.flights (season_id, type, name, airline, date, time, from_airport, to_airport, capacity)
select (select id from lt_season), t, n, 'طيران الاختبار', d, '10:00', a, b, 400 from (values
  ('ذهاب','LT-G1','2027-05-01','CAI','JED'), ('ذهاب','LT-G2','2027-05-02','CAI','JED'),
  ('إياب','LT-R1','2027-05-20','JED','CAI'), ('إياب','LT-R2','2027-05-21','JED','CAI')) v(t,n,d,a,b);

insert into public.buses (season_id, name, type, capacity)
select (select id from lt_season), 'باص اختبار ' || g, 'عادي', {BUS_CAP} from generate_series(1, {MAIN // BUS_CAP}) g;

insert into public.rooms (season_id, number, floor, capacity)
select (select id from lt_season), lpad(g::text, 3, '0'), ((g - 1) / 30 + 1)::text, {ROOM_CAP}
from generate_series(1, {MAIN // ROOM_CAP}) g;

insert into public.camps (season_id, page_type, gender, name, capacity)
select (select id from lt_season), p, gd, p || ' ' || gd || ' ' || k, 200
from (values ('منى'), ('عرفة')) a(p), (values ('ذكر'), ('أنثى')) b(gd), generate_series(1, 2) k;

create temp table lt_p (doc text, name text, gender text, dob text, room int, bus int, fam text, leg int) on commit drop;
insert into lt_p values
{(","+chr(10)).join(rows)};

insert into public.passengers (season_id, passport, name_ar, short_ar, gender, dob, family_id,
  room_id, bus_id, camp_mina_id, camp_arafa_id, flight_id, return_flight_id, hotel_type, flight_class)
select s.id, p.doc, p.name, p.name, p.gender, p.dob, p.fam,
  (select r.id from public.rooms r where r.season_id = s.id and r.number = lpad(p.room::text, 3, '0')),
  (select b.id from public.buses b where b.season_id = s.id and b.name = 'باص اختبار ' || p.bus),
  (select c.id from public.camps c where c.season_id = s.id and c.page_type = 'منى' and c.gender = p.gender
     and c.name = 'منى ' || p.gender || ' ' || ((p.room - 1) / 2 % 2 + 1)),
  (select c.id from public.camps c where c.season_id = s.id and c.page_type = 'عرفة' and c.gender = p.gender
     and c.name = 'عرفة ' || p.gender || ' ' || ((p.room - 1) / 2 % 2 + 1)),
  (select f.id from public.flights f where f.season_id = s.id and f.name = 'LT-G' || (p.leg + 1)),
  (select f.id from public.flights f where f.season_id = s.id and f.name = 'LT-R' || (p.leg + 1)),
  'رباعي', 'عادي'
from lt_p p, lt_season s;

-- document cohort: separate, no room/bus; keys point at harmless synthetic files uploaded in the
-- document phase only. Their photo triggers pilgrim-doc, so they are NEVER in the main pool.
insert into public.passengers (season_id, passport, name_ar, short_ar, gender, dob, photo_url, hajj_permit_url, flight_ticket_url)
select s.id, v.doc, v.name, v.name, v.gender, v.dob, v.ph, v.pm, v.tk from lt_season s, (values
{(","+chr(10)).join(doc_rows)}) v(doc, name, gender, dob, ph, pm, tk);

insert into public.announcements (season_id, title, body, priority, show_at)
select (select id from lt_season), 'تنبيه اختبار ' || g, 'نصّ تنبيه اختباري رقم ' || g,
  case when g = 1 then 'عاجل' else 'عادي' end, now() - interval '1 day'
from generate_series(1, 5) g;
commit;
"""
open(os.path.join(root, "seed.sql"), "w").write(sql)
ids = {"main": [{k: p[k] for k in ("doc", "day", "month", "year", "name")} for p in main],
       "docs": [{k: p[k] for k in ("doc", "day", "month", "year", "name")} for p in docs]}
json.dump(ids, open(os.path.join(root, "..", "k6", "identities.json"), "w"), ensure_ascii=False, indent=0)
print(f"seed.sql: {MAIN} main + {DOCS} document-cohort pilgrims; identities.json written")
